SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[ITCC_UserRole](
	[ITCC_UserRoleID] [int] IDENTITY(1,1) NOT NULL,
	[ITCC_UserID] [int] NOT NULL,
	[ITCC_RoleID] [int] NOT NULL,
	[ITCC_WebsiteID] [int] NULL,
 CONSTRAINT [PK_ITCC_UserRole] PRIMARY KEY CLUSTERED 
(
	[ITCC_UserRoleID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[ITCC_UserRole]  WITH CHECK ADD  CONSTRAINT [FK_ITCC_UserRole_ITCC_Role] FOREIGN KEY([ITCC_RoleID])
REFERENCES [dbo].[ITCC_Role] ([ITCC_RoleID])
GO

ALTER TABLE [dbo].[ITCC_UserRole] CHECK CONSTRAINT [FK_ITCC_UserRole_ITCC_Role]
GO

ALTER TABLE [dbo].[ITCC_UserRole]  WITH CHECK ADD  CONSTRAINT [FK_ITCC_UserRole_ITCC_User] FOREIGN KEY([ITCC_UserID])
REFERENCES [dbo].[ITCC_User] ([ITCC_UserID])
GO

ALTER TABLE [dbo].[ITCC_UserRole] CHECK CONSTRAINT [FK_ITCC_UserRole_ITCC_User]
GO


